import { Injectable, Inject } from '@nestjs/common';

@Injectable()
export class HomeService {

    getHomeContent() {
        return {
            advertiseList: [
                {
                    "clickCount": 0,
                    "endTime": "2023-11-08T09:04:05.000+00:00",
                    "id": 12,
                    "name": "小米推荐广告",
                    "orderCount": 0,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/xiaomi_banner_01.png",
                    "sort": 0,
                    "startTime": "2022-11-08T09:04:03.000+00:00",
                    "status": 1,
                    "type": 1,
                    "url": "/pages/brand/brandDetail?id=6"
                },
                {
                    "clickCount": 0,
                    "endTime": "2023-11-08T09:10:28.000+00:00",
                    "id": 13,
                    "name": "华为推荐广告",
                    "orderCount": 0,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/huawei_banner_01.png",
                    "sort": 0,
                    "startTime": "2022-11-08T09:10:27.000+00:00",
                    "status": 1,
                    "type": 1,
                    "url": "/pages/brand/brandDetail?id=3"
                },
                {
                    "clickCount": 0,
                    "endTime": "2023-11-08T09:12:55.000+00:00",
                    "id": 14,
                    "name": "苹果推荐广告",
                    "orderCount": 0,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/apple_banner_01.png",
                    "sort": 0,
                    "startTime": "2022-11-08T09:12:54.000+00:00",
                    "status": 1,
                    "type": 1,
                    "url": "/pages/brand/brandDetail?id=51"
                },
                {
                    "clickCount": 0,
                    "endTime": "2023-11-08T09:15:39.000+00:00",
                    "id": 15,
                    "name": "三星推荐广告",
                    "orderCount": 0,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_banner_01.png",
                    "sort": 0,
                    "startTime": "2022-11-08T09:15:38.000+00:00",
                    "status": 1,
                    "type": 1,
                    "url": "/pages/brand/brandDetail?id=2"
                },
                {
                    "clickCount": 0,
                    "endTime": "2023-11-08T09:20:11.000+00:00",
                    "id": 16,
                    "name": "OPPO推荐广告",
                    "orderCount": 0,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/oppo_banner_01.png",
                    "sort": 0,
                    "startTime": "2022-11-08T09:20:10.000+00:00",
                    "status": 1,
                    "type": 1,
                    "url": "/pages/brand/brandDetail?id=21"
                }
            ],
            brandList: [
                {
                    "bigPic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/xiaomi_banner_01.png",
                    "factoryStatus": 1,
                    "firstLetter": "M",
                    "id": 6,
                    "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20200607/5565f5a2N0b8169ae.jpg",
                    "name": "小米",
                    "productCommentCount": 100,
                    "productCount": 100,
                    "showStatus": 1,
                    "sort": 500
                },
                {
                    "bigPic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/huawei_banner_01.png",
                    "factoryStatus": 1,
                    "firstLetter": "H",
                    "id": 3,
                    "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20200607/5abf6f26N31658aa2.jpg",
                    "name": "华为",
                    "productCommentCount": 100,
                    "productCount": 100,
                    "showStatus": 1,
                    "sort": 100
                },
                {
                    "bigPic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/apple_banner_01.png",
                    "factoryStatus": 1,
                    "firstLetter": "A",
                    "id": 51,
                    "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20200607/49b30bb0377030d1.jpg",
                    "name": "苹果",
                    "productCommentCount": 200,
                    "productCount": 55,
                    "showStatus": 1,
                    "sort": 200
                },
                {
                    "bigPic": "http://img10.360buyimg.com/cms/jfs/t1/133148/4/1605/470028/5edaf5ccEd7a687a9/e0a007631361ff75.jpg",
                    "factoryStatus": 1,
                    "firstLetter": "H",
                    "id": 50,
                    "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20200607/5a5c69b9N5d6c5696.jpg",
                    "name": "海澜之家",
                    "productCommentCount": 300,
                    "productCount": 66,
                    "showStatus": 1,
                    "sort": 200
                },
                {
                    "bigPic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/oppo_banner_01.png",
                    "factoryStatus": 1,
                    "firstLetter": "O",
                    "id": 21,
                    "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180607/timg(6).jpg",
                    "name": "OPPO",
                    "productCommentCount": 500,
                    "productCount": 88,
                    "showStatus": 1,
                    "sort": 0
                },
                {
                    "bigPic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_banner_01.png",
                    "factoryStatus": 1,
                    "firstLetter": "S",
                    "id": 2,
                    "logo": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20200607/57201b47N7bf15715.jpg",
                    "name": "三星",
                    "productCommentCount": 100,
                    "productCount": 100,
                    "showStatus": 1,
                    "sort": 100
                }
            ],
            homeFlashPromotion: {
                "endTime": 0,
                "nextEndTime": 7200000,
                "nextStartTime": 0,
                "startTime": 0,
                "productList": [
                    {
                        "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/redmi_k50_02.jpg",
                        "brandId": 6,
                        "brandName": "小米",
                        "deleteStatus": 0,
                        "description": "",
                        "detailTitle": "",
                        "feightTemplateId": 0,
                        "giftGrowth": 0,
                        "giftPoint": 0,
                        "id": 41,
                        "keywords": "",
                        "lowStock": 0,
                        "name": "Redmi K50 天玑8100 2K柔性直屏 OIS光学防抖 67W快充 5500mAh大电量",
                        "newStatus": 0,
                        "note": "",
                        "originalPrice": 2099,
                        "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/redmi_k50_01.jpg",
                        "previewStatus": 0,
                        "price": 2099,
                        "productAttributeCategoryId": 3,
                        "productCategoryId": 19,
                        "productCategoryName": "手机通讯",
                        "productSn": "100035246702",
                        "promotionPerLimit": 0,
                        "promotionType": 0,
                        "publishStatus": 1,
                        "recommandStatus": 0,
                        "sale": 0,
                        "serviceIds": "",
                        "sort": 0,
                        "stock": 1000,
                        "subTitle": "【品质好物】天玑8100，2K直屏，5500mAh大电量【Note12Pro火热抢购中】 ",
                        "unit": "",
                        "usePointLimit": 0,
                        "verifyStatus": 0,
                        "weight": 0
                    },
                    {
                        "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/huawei_mate50_02.jpg",
                        "brandId": 3,
                        "brandName": "华为",
                        "deleteStatus": 0,
                        "description": "",
                        "detailTitle": "",
                        "feightTemplateId": 0,
                        "giftGrowth": 0,
                        "giftPoint": 0,
                        "id": 42,
                        "keywords": "",
                        "lowStock": 0,
                        "name": "HUAWEI Mate 50 直屏旗舰 超光变XMAGE影像 北斗卫星消息",
                        "newStatus": 0,
                        "note": "",
                        "originalPrice": 4999,
                        "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/huawei_mate50_01.jpg",
                        "previewStatus": 0,
                        "price": 4999,
                        "productAttributeCategoryId": 3,
                        "productCategoryId": 19,
                        "productCategoryName": "手机通讯",
                        "productSn": "100035295081",
                        "promotionPerLimit": 0,
                        "promotionType": 0,
                        "publishStatus": 1,
                        "recommandStatus": 0,
                        "sale": 0,
                        "serviceIds": "",
                        "sort": 0,
                        "stock": 1000,
                        "subTitle": "【华为Mate50新品上市】内置66W华为充电套装，超光变XMAGE影像,北斗卫星消息，鸿蒙操作系统3.0！立即抢购！华为新品可持续计划，猛戳》 ",
                        "unit": "",
                        "usePointLimit": 0,
                        "verifyStatus": 0,
                        "weight": 0
                    },
                    {
                        "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/wanhe_16L_01.jpg",
                        "brandId": 1,
                        "brandName": "万和",
                        "deleteStatus": 0,
                        "description": "",
                        "detailTitle": "",
                        "feightTemplateId": 0,
                        "giftGrowth": 0,
                        "giftPoint": 0,
                        "id": 43,
                        "keywords": "",
                        "lowStock": 0,
                        "name": "万和（Vanward)燃气热水器天然气家用四重防冻直流变频节能全新升级增压水伺服恒温高抗风",
                        "newStatus": 0,
                        "note": "",
                        "originalPrice": 1799,
                        "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/wanhe_13L_01.png",
                        "previewStatus": 0,
                        "price": 1799,
                        "productAttributeCategoryId": 14,
                        "productCategoryId": 39,
                        "productCategoryName": "厨卫大电",
                        "productSn": "10044060351752",
                        "promotionPerLimit": 0,
                        "promotionType": 0,
                        "publishStatus": 1,
                        "recommandStatus": 0,
                        "sale": 0,
                        "serviceIds": "",
                        "sort": 0,
                        "stock": 1000,
                        "subTitle": "【家电11.11享低价，抢到手价不高于1199】【发布种草秀享好礼！同价11.11买贵补差】爆款超一级能效零冷水】 ",
                        "unit": "",
                        "usePointLimit": 0,
                        "verifyStatus": 0,
                        "weight": 0
                    },
                    {
                        "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_ssd_01.jpg",
                        "brandId": 2,
                        "brandName": "三星",
                        "deleteStatus": 0,
                        "description": "",
                        "detailTitle": "",
                        "feightTemplateId": 0,
                        "giftGrowth": 0,
                        "giftPoint": 0,
                        "id": 44,
                        "keywords": "",
                        "lowStock": 0,
                        "name": "三星（SAMSUNG）500GB SSD固态硬盘 M.2接口(NVMe协议)",
                        "newStatus": 0,
                        "note": "",
                        "originalPrice": 369,
                        "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_ssd_02.jpg",
                        "previewStatus": 0,
                        "price": 369,
                        "productAttributeCategoryId": 15,
                        "productCategoryId": 55,
                        "productCategoryName": "硬盘",
                        "productSn": "100018768480",
                        "promotionPerLimit": 0,
                        "promotionType": 0,
                        "publishStatus": 1,
                        "recommandStatus": 0,
                        "sale": 0,
                        "serviceIds": "",
                        "sort": 0,
                        "stock": 1000,
                        "subTitle": "【满血无缓存！进店抽百元E卡，部分型号白条三期免息】兼具速度与可靠性！读速高达3500MB/s，全功率模式！点击 ",
                        "unit": "",
                        "usePointLimit": 0,
                        "verifyStatus": 0,
                        "weight": 0
                    },
                    {
                        "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/oppo_r8_02.jpg",
                        "brandId": 21,
                        "brandName": "OPPO",
                        "deleteStatus": 0,
                        "description": "",
                        "detailTitle": "",
                        "feightTemplateId": 0,
                        "giftGrowth": 0,
                        "giftPoint": 0,
                        "id": 45,
                        "keywords": "",
                        "lowStock": 0,
                        "name": "OPPO Reno8 8GB+128GB 鸢尾紫 新配色上市 80W超级闪充 5000万水光人像三摄",
                        "newStatus": 0,
                        "note": "",
                        "originalPrice": 2299,
                        "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/oppo_r8_01.jpg",
                        "previewStatus": 0,
                        "price": 2299,
                        "productAttributeCategoryId": 3,
                        "productCategoryId": 19,
                        "productCategoryName": "手机通讯",
                        "productSn": "10052147850350",
                        "promotionEndTime": "2022-11-24T16:00:00.000+00:00",
                        "promotionPerLimit": 0,
                        "promotionPrice": 999,
                        "promotionStartTime": "2022-11-09T08:15:50.000+00:00",
                        "promotionType": 4,
                        "publishStatus": 1,
                        "recommandStatus": 0,
                        "sale": 0,
                        "serviceIds": "",
                        "sort": 0,
                        "stock": 1000,
                        "subTitle": "【11.11提前购机享价保，好货不用等，系统申请一键价保补差!】【Reno8Pro爆款优惠】 ",
                        "unit": "",
                        "usePointLimit": 0,
                        "verifyStatus": 0,
                        "weight": 0
                    }
                ]
            },
            hotProductList: [
                {
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/ipad_002.jpg",
                    "brandId": 51,
                    "brandName": "苹果",
                    "deleteStatus": 0,
                    "description": "",
                    "detailTitle": "",
                    "feightTemplateId": 0,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "id": 38,
                    "keywords": "",
                    "lowStock": 0,
                    "name": "Apple iPad 10.9英寸平板电脑 2022年款",
                    "newStatus": 0,
                    "note": "",
                    "originalPrice": 3599,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/ipad_001.jpg",
                    "previewStatus": 0,
                    "price": 3599,
                    "productAttributeCategoryId": 3,
                    "productCategoryId": 53,
                    "productCategoryName": "平板电脑",
                    "productSn": "100044025833",
                    "promotionPerLimit": 0,
                    "promotionType": 0,
                    "publishStatus": 1,
                    "recommandStatus": 0,
                    "sale": 0,
                    "serviceIds": "1,2,3",
                    "sort": 0,
                    "stock": 1000,
                    "subTitle": "【11.11大爱超大爱】iPad9代限量抢购，价格优惠，更享以旧换新至高补贴325元！！快来抢购吧！！ ",
                    "unit": "",
                    "usePointLimit": 0,
                    "verifyStatus": 0,
                    "weight": 0
                },
                {
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/xiaomi_computer_002.jpg",
                    "brandId": 6,
                    "brandName": "小米",
                    "deleteStatus": 0,
                    "description": "",
                    "detailTitle": "",
                    "feightTemplateId": 0,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "id": 39,
                    "keywords": "",
                    "lowStock": 0,
                    "name": "小米 Xiaomi Book Pro 14 2022 锐龙版 2.8K超清大师屏 高端轻薄笔记本电脑",
                    "newStatus": 0,
                    "note": "",
                    "originalPrice": 5599,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/xiaomi_computer_001.jpg",
                    "previewStatus": 0,
                    "price": 5599,
                    "productAttributeCategoryId": 13,
                    "productCategoryId": 54,
                    "productCategoryName": "笔记本",
                    "productSn": "100023207945",
                    "promotionPerLimit": 0,
                    "promotionType": 0,
                    "publishStatus": 1,
                    "recommandStatus": 1,
                    "sale": 0,
                    "serviceIds": "",
                    "sort": 0,
                    "stock": 500,
                    "subTitle": "【双十一大促来袭】指定型号至高优惠1000，以旧换新至高补贴1000元，晒单赢好礼",
                    "unit": "",
                    "usePointLimit": 0,
                    "verifyStatus": 0,
                    "weight": 0
                },
                {
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_ssd_01.jpg",
                    "brandId": 2,
                    "brandName": "三星",
                    "deleteStatus": 0,
                    "description": "",
                    "detailTitle": "",
                    "feightTemplateId": 0,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "id": 44,
                    "keywords": "",
                    "lowStock": 0,
                    "name": "三星（SAMSUNG）500GB SSD固态硬盘 M.2接口(NVMe协议)",
                    "newStatus": 0,
                    "note": "",
                    "originalPrice": 369,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221108/sanxing_ssd_02.jpg",
                    "previewStatus": 0,
                    "price": 369,
                    "productAttributeCategoryId": 15,
                    "productCategoryId": 55,
                    "productCategoryName": "硬盘",
                    "productSn": "100018768480",
                    "promotionPerLimit": 0,
                    "promotionType": 0,
                    "publishStatus": 1,
                    "recommandStatus": 0,
                    "sale": 0,
                    "serviceIds": "",
                    "sort": 0,
                    "stock": 1000,
                    "subTitle": "【满血无缓存！进店抽百元E卡，部分型号白条三期免息】兼具速度与可靠性！读速高达3500MB/s，全功率模式！点击 ",
                    "unit": "",
                    "usePointLimit": 0,
                    "verifyStatus": 0,
                    "weight": 0
                },
                {
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/wanhe_16L_01.jpg",
                    "brandId": 1,
                    "brandName": "万和",
                    "deleteStatus": 0,
                    "description": "",
                    "detailTitle": "",
                    "feightTemplateId": 0,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "id": 43,
                    "keywords": "",
                    "lowStock": 0,
                    "name": "万和（Vanward)燃气热水器天然气家用四重防冻直流变频节能全新升级增压水伺服恒温高抗风",
                    "newStatus": 0,
                    "note": "",
                    "originalPrice": 1799,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/wanhe_13L_01.png",
                    "previewStatus": 0,
                    "price": 1799,
                    "productAttributeCategoryId": 14,
                    "productCategoryId": 39,
                    "productCategoryName": "厨卫大电",
                    "productSn": "10044060351752",
                    "promotionPerLimit": 0,
                    "promotionType": 0,
                    "publishStatus": 1,
                    "recommandStatus": 0,
                    "sale": 0,
                    "serviceIds": "",
                    "sort": 0,
                    "stock": 1000,
                    "subTitle": "【家电11.11享低价，抢到手价不高于1199】【发布种草秀享好礼！同价11.11买贵补差】爆款超一级能效零冷水】 ",
                    "unit": "",
                    "usePointLimit": 0,
                    "verifyStatus": 0,
                    "weight": 0
                }
            ],
            newProductList: [
                {
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/xiaomi_12_pro_02.jpg",
                    "brandId": 6,
                    "brandName": "小米",
                    "deleteStatus": 0,
                    "description": "",
                    "detailTitle": "",
                    "feightTemplateId": 0,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "id": 40,
                    "keywords": "",
                    "lowStock": 0,
                    "name": "小米12 Pro 天玑版 天玑9000+处理器 5000万疾速影像 2K超视感屏 120Hz高刷 67W快充",
                    "newStatus": 0,
                    "note": "",
                    "originalPrice": 2999,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/xiaomi_12_pro_01.jpg",
                    "previewStatus": 0,
                    "price": 2999,
                    "productAttributeCategoryId": 3,
                    "productCategoryId": 19,
                    "productCategoryName": "手机通讯",
                    "productSn": "100027789721",
                    "promotionPerLimit": 0,
                    "promotionType": 4,
                    "publishStatus": 1,
                    "recommandStatus": 1,
                    "sale": 0,
                    "serviceIds": "",
                    "sort": 0,
                    "stock": 500,
                    "subTitle": "天玑9000+处理器、5160mAh大电量、2KAmoled超视感屏【点击购买小米11Ultra，戳】 ",
                    "unit": "",
                    "usePointLimit": 0,
                    "verifyStatus": 0,
                    "weight": 0
                },
                {
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/redmi_k50_02.jpg",
                    "brandId": 6,
                    "brandName": "小米",
                    "deleteStatus": 0,
                    "description": "",
                    "detailTitle": "",
                    "feightTemplateId": 0,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "id": 41,
                    "keywords": "",
                    "lowStock": 0,
                    "name": "Redmi K50 天玑8100 2K柔性直屏 OIS光学防抖 67W快充 5500mAh大电量",
                    "newStatus": 0,
                    "note": "",
                    "originalPrice": 2099,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/redmi_k50_01.jpg",
                    "previewStatus": 0,
                    "price": 2099,
                    "productAttributeCategoryId": 3,
                    "productCategoryId": 19,
                    "productCategoryName": "手机通讯",
                    "productSn": "100035246702",
                    "promotionPerLimit": 0,
                    "promotionType": 0,
                    "publishStatus": 1,
                    "recommandStatus": 0,
                    "sale": 0,
                    "serviceIds": "",
                    "sort": 0,
                    "stock": 1000,
                    "subTitle": "【品质好物】天玑8100，2K直屏，5500mAh大电量【Note12Pro火热抢购中】 ",
                    "unit": "",
                    "usePointLimit": 0,
                    "verifyStatus": 0,
                    "weight": 0
                },
                {
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/xiaomi_computer_002.jpg",
                    "brandId": 6,
                    "brandName": "小米",
                    "deleteStatus": 0,
                    "description": "",
                    "detailTitle": "",
                    "feightTemplateId": 0,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "id": 39,
                    "keywords": "",
                    "lowStock": 0,
                    "name": "小米 Xiaomi Book Pro 14 2022 锐龙版 2.8K超清大师屏 高端轻薄笔记本电脑",
                    "newStatus": 0,
                    "note": "",
                    "originalPrice": 5599,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/xiaomi_computer_001.jpg",
                    "previewStatus": 0,
                    "price": 5599,
                    "productAttributeCategoryId": 13,
                    "productCategoryId": 54,
                    "productCategoryName": "笔记本",
                    "productSn": "100023207945",
                    "promotionPerLimit": 0,
                    "promotionType": 0,
                    "publishStatus": 1,
                    "recommandStatus": 1,
                    "sale": 0,
                    "serviceIds": "",
                    "sort": 0,
                    "stock": 500,
                    "subTitle": "【双十一大促来袭】指定型号至高优惠1000，以旧换新至高补贴1000元，晒单赢好礼",
                    "unit": "",
                    "usePointLimit": 0,
                    "verifyStatus": 0,
                    "weight": 0
                },
                {
                    "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_002.jpg,http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_003.jpg,http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_004.jpg",
                    "brandId": 51,
                    "brandName": "苹果",
                    "deleteStatus": 0,
                    "description": "",
                    "detailTitle": "",
                    "feightTemplateId": 0,
                    "giftGrowth": 0,
                    "giftPoint": 0,
                    "id": 37,
                    "keywords": "",
                    "lowStock": 0,
                    "name": "Apple iPhone 14 (A2884) 128GB 支持移动联通电信5G 双卡双待手机",
                    "newStatus": 0,
                    "note": "",
                    "originalPrice": 5999,
                    "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_001.jpg",
                    "previewStatus": 0,
                    "price": 5999,
                    "productAttributeCategoryId": 3,
                    "productCategoryId": 19,
                    "productCategoryName": "手机通讯",
                    "productSn": "100038005189",
                    "promotionPerLimit": 0,
                    "promotionType": 0,
                    "publishStatus": 1,
                    "recommandStatus": 0,
                    "sale": 0,
                    "serviceIds": "1,2,3",
                    "sort": 200,
                    "stock": 1000,
                    "subTitle": "【11.11大爱超大爱】指定iPhone14产品限时限量领券立减601元！！！部分iPhone产品现货抢购确认收货即送原厂手机壳10元优惠券！！！猛戳 ",
                    "unit": "",
                    "usePointLimit": 0,
                    "verifyStatus": 0,
                    "weight": 208
                }
            ],
            subjectList: []
        };
    }

    // 推荐产品列表
    getHomeRecommendProductList() {
        return [
            {
                "albumPics": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180607/5ab46a3cN616bdc41.jpg,http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180607/5ac1bf5fN2522b9dc.jpg",
                "brandId": 3,
                "brandName": "华为",
                "deleteStatus": 0,
                "detailTitle": "",
                "feightTemplateId": 0,
                "giftGrowth": 3788,
                "giftPoint": 3788,
                "id": 26,
                "keywords": "",
                "lowStock": 0,
                "name": "华为 HUAWEI P20 ",
                "newStatus": 1,
                "note": "",
                "originalPrice": 4288,
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180607/5ac1bf58Ndefaac16.jpg",
                "previewStatus": 1,
                "price": 3788,
                "productAttributeCategoryId": 3,
                "productCategoryId": 19,
                "productCategoryName": "手机通讯",
                "productSn": "6946605",
                "promotionEndTime": "2023-01-30T16:00:00.000+00:00",
                "promotionPerLimit": 0,
                "promotionPrice": 3659,
                "promotionStartTime": "2023-01-10T07:49:38.000+00:00",
                "promotionType": 1,
                "publishStatus": 1,
                "recommandStatus": 1,
                "sale": 100,
                "serviceIds": "2,3,1",
                "sort": 100,
                "stock": 1000,
                "subTitle": "AI智慧全面屏 6GB +64GB 亮黑色 全网通版 移动联通电信4G手机 双卡双待手机 双卡双待",
                "unit": "件",
                "usePointLimit": 0,
                "verifyStatus": 0,
                "weight": 0
            },
            {
                "albumPics": "",
                "brandId": 6,
                "brandName": "小米",
                "deleteStatus": 0,
                "detailTitle": "",
                "feightTemplateId": 0,
                "giftGrowth": 2699,
                "giftPoint": 2699,
                "id": 27,
                "keywords": "",
                "lowStock": 0,
                "name": "小米8 全面屏游戏智能手机 6GB+64GB 黑色 全网通4G 双卡双待",
                "newStatus": 1,
                "note": "",
                "originalPrice": 2699,
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/xiaomi.jpg",
                "previewStatus": 0,
                "price": 2699,
                "productAttributeCategoryId": 3,
                "productCategoryId": 19,
                "productCategoryName": "手机通讯",
                "productSn": "7437788",
                "promotionPerLimit": 0,
                "promotionType": 3,
                "publishStatus": 1,
                "recommandStatus": 1,
                "sale": 99,
                "serviceIds": "1",
                "sort": 0,
                "stock": 100,
                "subTitle": "骁龙845处理器，红外人脸解锁，AI变焦双摄，AI语音助手小米6X低至1299，点击抢购",
                "unit": "",
                "usePointLimit": 0,
                "verifyStatus": 0,
                "weight": 0
            },
            {
                "albumPics": "",
                "brandId": 6,
                "brandName": "小米",
                "deleteStatus": 0,
                "detailTitle": "",
                "feightTemplateId": 0,
                "giftGrowth": 649,
                "giftPoint": 649,
                "id": 28,
                "keywords": "",
                "lowStock": 0,
                "name": "小米 红米5A 全网通版 3GB+32GB 香槟金 移动联通电信4G手机 双卡双待",
                "newStatus": 1,
                "note": "",
                "originalPrice": 649,
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/5a9d248cN071f4959.jpg",
                "previewStatus": 0,
                "price": 649,
                "productAttributeCategoryId": 3,
                "productCategoryId": 19,
                "productCategoryName": "手机通讯",
                "productSn": "7437789",
                "promotionPerLimit": 0,
                "promotionType": 4,
                "publishStatus": 1,
                "recommandStatus": 1,
                "sale": 98,
                "serviceIds": "",
                "sort": 0,
                "stock": 100,
                "subTitle": "8天超长待机，137g轻巧机身，高通骁龙处理器小米6X低至1299，点击抢购",
                "unit": "",
                "usePointLimit": 0,
                "verifyStatus": 0,
                "weight": 0
            },
            {
                "albumPics": "",
                "brandId": 51,
                "brandName": "苹果",
                "deleteStatus": 0,
                "detailTitle": "",
                "feightTemplateId": 0,
                "giftGrowth": 5499,
                "giftPoint": 5499,
                "id": 29,
                "keywords": "",
                "lowStock": 0,
                "name": "Apple iPhone 8 Plus 64GB 红色特别版 移动联通电信4G手机",
                "newStatus": 1,
                "note": "",
                "originalPrice": 5499,
                "pic": "http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/5acc5248N6a5f81cd.jpg",
                "previewStatus": 0,
                "price": 5499,
                "productAttributeCategoryId": 3,
                "productCategoryId": 19,
                "productCategoryName": "手机通讯",
                "productSn": "7437799",
                "promotionEndTime": "2020-05-29T16:00:00.000+00:00",
                "promotionPerLimit": 0,
                "promotionPrice": 4799,
                "promotionStartTime": "2020-05-04T07:12:54.000+00:00",
                "promotionType": 1,
                "publishStatus": 1,
                "recommandStatus": 1,
                "sale": 97,
                "serviceIds": "1,2,3",
                "sort": 0,
                "stock": 100,
                "subTitle": "【限时限量抢购】Apple产品年中狂欢节，好物尽享，美在智慧！速来 >> 勾选[保障服务][原厂保2年]，获得AppleCare+全方位服务计划，原厂延保售后无忧。",
                "unit": "",
                "usePointLimit": 0,
                "verifyStatus": 0,
                "weight": 0
            }
        ];
    }
}
